//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyenvancu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public ADMIN()
        {
            this.ADMINS1 = new HashSet<ADMIN>();
            this.CONTENTs = new HashSet<CONTENT>();
            this.products = new HashSet<product>();
        }
    
        public string id { get; set; }
        public byte[] passwords { get; set; }
        public byte[] passwords_salt { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string addressid { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> idrank { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public string admin_create { get; set; }
        public bool is_active { get; set; }
        public Nullable<int> idImg { get; set; }
    
        public virtual ICollection<ADMIN> ADMINS1 { get; set; }
        public virtual ADMIN ADMIN1 { get; set; }
        public virtual ICollection<CONTENT> CONTENTs { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual IMG IMG { get; set; }
        public virtual rank rank { get; set; }
    }
}
