//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyenvancu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public int idcontent { get; set; }
        public int idImg { get; set; }
    
        public virtual ICollection<product> products { get; set; }
        public virtual CONTENT CONTENT { get; set; }
        public virtual IMG IMG { get; set; }
    }
}
