//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyenvancu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT
    {
        public CONTENT()
        {
            this.companies = new HashSet<company>();
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string texts { get; set; }
        public string IDADMINS { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual ICollection<company> companies { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
