//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyenvancu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nguyenvancudbEntities : DbContext
    {
        public nguyenvancudbEntities()
            : base("name=nguyenvancudbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINS { get; set; }
        public DbSet<cart> carts { get; set; }
        public DbSet<COMMENT> COMMENTs { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<CONTENT> CONTENTs { get; set; }
        public DbSet<detailhistorycart> detailhistorycarts { get; set; }
        public DbSet<detailproduct> detailproducts { get; set; }
        public DbSet<historycart> historycarts { get; set; }
        public DbSet<IMG> IMGs { get; set; }
        public DbSet<LIST_IMG> LIST_IMG { get; set; }
        public DbSet<menu> menus { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<property> properties { get; set; }
        public DbSet<rank> ranks { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<USER> USERS { get; set; }
    }
}
