//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyenvancu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.carts = new HashSet<cart>();
            this.COMMENTs = new HashSet<COMMENT>();
            this.detailhistorycarts = new HashSet<detailhistorycart>();
            this.detailproducts = new HashSet<detailproduct>();
            this.USERS = new HashSet<USER>();
        }
    
        public int id { get; set; }
        public string names { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<bool> ispromotion { get; set; }
        public Nullable<int> price_promotion { get; set; }
        public Nullable<bool> is_available { get; set; }
        public int idcontent { get; set; }
        public Nullable<int> idmenu { get; set; }
        public Nullable<int> idcompany { get; set; }
        public string idADMINSLASTMDF { get; set; }
        public Nullable<int> id_list_img { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual ICollection<cart> carts { get; set; }
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual company company { get; set; }
        public virtual CONTENT CONTENT { get; set; }
        public virtual ICollection<detailhistorycart> detailhistorycarts { get; set; }
        public virtual ICollection<detailproduct> detailproducts { get; set; }
        public virtual LIST_IMG LIST_IMG { get; set; }
        public virtual menu menu { get; set; }
        public virtual ICollection<USER> USERS { get; set; }
    }
}
