//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nguyenvancu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rank
    {
        public rank()
        {
            this.ADMINS = new HashSet<ADMIN>();
        }
    
        public int id { get; set; }
        public string names { get; set; }
    
        public virtual ICollection<ADMIN> ADMINS { get; set; }
    }
}
