USE [nguyenvancudb]
GO
/****** Object:  Table [dbo].[ADMINS]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMINS](
	[id] [varchar](16) NOT NULL,
	[passwords] [varbinary](64) NULL,
	[passwords_salt] [varbinary](64) NULL,
	[lastname] [varchar](32) NULL,
	[firstname] [varchar](10) NULL,
	[addressid] [nvarchar](100) NULL,
	[phone] [varchar](15) NULL,
	[email] [varchar](32) NULL,
	[idrank] [int] NULL,
	[date_create] [datetime] NULL,
	[admin_create] [varchar](16) NULL,
	[is_active] [bit] NOT NULL,
	[idImg] [int] NULL,
 CONSTRAINT [PK_ADMINS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[cart]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cart](
	[iduser] [varchar](16) NOT NULL,
	[idproduct] [int] NOT NULL,
	[COUNT] [int] NULL,
 CONSTRAINT [pk_cart] PRIMARY KEY CLUSTERED 
(
	[iduser] ASC,
	[idproduct] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMMENT]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMMENT](
	[idproduct] [int] NOT NULL,
	[iduser] [varchar](16) NOT NULL,
	[RATE] [float] NOT NULL,
	[COMMENT] [nvarchar](100) NOT NULL,
 CONSTRAINT [pk_COMMENT] PRIMARY KEY CLUSTERED 
(
	[idproduct] ASC,
	[iduser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[company]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[company](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idcontent] [int] NOT NULL,
	[idImg] [int] NOT NULL,
 CONSTRAINT [PK_company] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONTENT]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONTENT](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[title] [nvarchar](16) NULL,
	[texts] [nvarchar](1000) NULL,
	[IDADMINS] [varchar](16) NOT NULL,
 CONSTRAINT [PK_CONTENT] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[title] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[title] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[detailhistorycart]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[detailhistorycart](
	[idhistorycart] [int] NOT NULL,
	[idproduct] [int] NOT NULL,
	[COUNT] [int] NULL,
 CONSTRAINT [pk_detailhistorycart] PRIMARY KEY CLUSTERED 
(
	[idhistorycart] ASC,
	[idproduct] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[detailproduct]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[detailproduct](
	[idproduct] [int] NOT NULL,
	[idproperties] [int] NOT NULL,
	[datas] [nvarchar](1000) NULL,
 CONSTRAINT [PK_detailproduct] PRIMARY KEY CLUSTERED 
(
	[idproduct] ASC,
	[idproperties] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[history]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[history](
	[iduser] [varchar](16) NOT NULL,
	[idproduct] [int] NOT NULL,
 CONSTRAINT [pk_history] PRIMARY KEY CLUSTERED 
(
	[iduser] ASC,
	[idproduct] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[historycart]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[historycart](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[iduser] [varchar](16) NOT NULL,
	[datecart] [date] NOT NULL,
	[iscomplete] [bit] NULL,
 CONSTRAINT [pk_historycart] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IMG]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMG](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[link] [varchar](100) NULL,
	[ten] [nvarchar](50) NULL,
	[owner_id] [varchar](100) NULL,
	[tableowner] [varchar](100) NULL,
	[mota] [varchar](100) NULL,
	[id_LIST_IMG] [int] NULL,
 CONSTRAINT [PK_Img] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[link] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[link] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LIST_IMG]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LIST_IMG](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[class] [varchar](30) NULL,
	[id_user] [varchar](16) NULL,
	[date_update] [date] NULL,
 CONSTRAINT [PK_LIST_IMG] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[menu]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[menu](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[names] [nvarchar](30) NOT NULL,
	[is_active] [bit] NOT NULL,
	[lv] [int] NOT NULL,
	[menuownerid] [int] NULL,
 CONSTRAINT [PK_menulv1] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[product]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[product](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[names] [nvarchar](30) NULL,
	[price] [int] NULL,
	[ispromotion] [bit] NULL,
	[price_promotion] [int] NULL,
	[is_available] [bit] NULL,
	[idcontent] [int] NOT NULL,
	[idmenu] [int] NULL,
	[idcompany] [int] NULL,
	[idADMINSLASTMDF] [varchar](16) NULL,
	[id_list_img] [int] NULL,
 CONSTRAINT [PK_product] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[properties]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[properties](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[names] [nvarchar](16) NULL,
 CONSTRAINT [PK_properties] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[names] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[names] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[rank]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[rank](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[names] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 4/9/2023 5:18:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[id] [varchar](16) NOT NULL,
	[passwords] [varchar](32) NULL,
	[lastname] [varchar](32) NULL,
	[firstname] [varchar](10) NULL,
	[addressid] [nvarchar](100) NULL,
	[phone] [varchar](15) NULL,
	[email] [varchar](32) NULL,
	[rank] [nvarchar](20) NULL,
	[datecreate] [datetime] NULL,
	[is_active] [bit] NOT NULL,
	[idImg] [int] NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADMINS] ADD  DEFAULT ((1)) FOR [is_active]
GO
ALTER TABLE [dbo].[menu] ADD  DEFAULT ((1)) FOR [is_active]
GO
ALTER TABLE [dbo].[product] ADD  DEFAULT ((0)) FOR [ispromotion]
GO
ALTER TABLE [dbo].[product] ADD  DEFAULT ((1)) FOR [is_available]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT ((1)) FOR [is_active]
GO
ALTER TABLE [dbo].[ADMINS]  WITH CHECK ADD  CONSTRAINT [FK_ADMINS_ADMINS] FOREIGN KEY([admin_create])
REFERENCES [dbo].[ADMINS] ([id])
GO
ALTER TABLE [dbo].[ADMINS] CHECK CONSTRAINT [FK_ADMINS_ADMINS]
GO
ALTER TABLE [dbo].[ADMINS]  WITH CHECK ADD  CONSTRAINT [FK_Img_ADMINS] FOREIGN KEY([idImg])
REFERENCES [dbo].[IMG] ([id])
GO
ALTER TABLE [dbo].[ADMINS] CHECK CONSTRAINT [FK_Img_ADMINS]
GO
ALTER TABLE [dbo].[ADMINS]  WITH CHECK ADD  CONSTRAINT [FK_rank_ADMINS] FOREIGN KEY([idrank])
REFERENCES [dbo].[rank] ([id])
GO
ALTER TABLE [dbo].[ADMINS] CHECK CONSTRAINT [FK_rank_ADMINS]
GO
ALTER TABLE [dbo].[cart]  WITH CHECK ADD  CONSTRAINT [FK_product_cart] FOREIGN KEY([idproduct])
REFERENCES [dbo].[product] ([id])
GO
ALTER TABLE [dbo].[cart] CHECK CONSTRAINT [FK_product_cart]
GO
ALTER TABLE [dbo].[cart]  WITH CHECK ADD  CONSTRAINT [FK_user_cart] FOREIGN KEY([iduser])
REFERENCES [dbo].[USERS] ([id])
GO
ALTER TABLE [dbo].[cart] CHECK CONSTRAINT [FK_user_cart]
GO
ALTER TABLE [dbo].[COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_product_COMMENT] FOREIGN KEY([idproduct])
REFERENCES [dbo].[product] ([id])
GO
ALTER TABLE [dbo].[COMMENT] CHECK CONSTRAINT [FK_product_COMMENT]
GO
ALTER TABLE [dbo].[COMMENT]  WITH CHECK ADD  CONSTRAINT [FK_USER_COMMENT] FOREIGN KEY([iduser])
REFERENCES [dbo].[USERS] ([id])
GO
ALTER TABLE [dbo].[COMMENT] CHECK CONSTRAINT [FK_USER_COMMENT]
GO
ALTER TABLE [dbo].[company]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT_company] FOREIGN KEY([idcontent])
REFERENCES [dbo].[CONTENT] ([id])
GO
ALTER TABLE [dbo].[company] CHECK CONSTRAINT [FK_CONTENT_company]
GO
ALTER TABLE [dbo].[company]  WITH CHECK ADD  CONSTRAINT [FK_Img_company] FOREIGN KEY([idImg])
REFERENCES [dbo].[IMG] ([id])
GO
ALTER TABLE [dbo].[company] CHECK CONSTRAINT [FK_Img_company]
GO
ALTER TABLE [dbo].[CONTENT]  WITH CHECK ADD  CONSTRAINT [FK_ADMINS_CONTENT] FOREIGN KEY([IDADMINS])
REFERENCES [dbo].[ADMINS] ([id])
GO
ALTER TABLE [dbo].[CONTENT] CHECK CONSTRAINT [FK_ADMINS_CONTENT]
GO
ALTER TABLE [dbo].[detailhistorycart]  WITH CHECK ADD  CONSTRAINT [FK_historycart_detailhistorycart] FOREIGN KEY([idhistorycart])
REFERENCES [dbo].[historycart] ([Id])
GO
ALTER TABLE [dbo].[detailhistorycart] CHECK CONSTRAINT [FK_historycart_detailhistorycart]
GO
ALTER TABLE [dbo].[detailhistorycart]  WITH CHECK ADD  CONSTRAINT [FK_product_detailhistorycart] FOREIGN KEY([idproduct])
REFERENCES [dbo].[product] ([id])
GO
ALTER TABLE [dbo].[detailhistorycart] CHECK CONSTRAINT [FK_product_detailhistorycart]
GO
ALTER TABLE [dbo].[detailproduct]  WITH CHECK ADD  CONSTRAINT [FK_product_detailproduct] FOREIGN KEY([idproduct])
REFERENCES [dbo].[product] ([id])
GO
ALTER TABLE [dbo].[detailproduct] CHECK CONSTRAINT [FK_product_detailproduct]
GO
ALTER TABLE [dbo].[detailproduct]  WITH CHECK ADD  CONSTRAINT [FK_properties_detailproduct] FOREIGN KEY([idproperties])
REFERENCES [dbo].[properties] ([id])
GO
ALTER TABLE [dbo].[detailproduct] CHECK CONSTRAINT [FK_properties_detailproduct]
GO
ALTER TABLE [dbo].[history]  WITH CHECK ADD  CONSTRAINT [FK_product_history] FOREIGN KEY([idproduct])
REFERENCES [dbo].[product] ([id])
GO
ALTER TABLE [dbo].[history] CHECK CONSTRAINT [FK_product_history]
GO
ALTER TABLE [dbo].[history]  WITH CHECK ADD  CONSTRAINT [FK_user_history] FOREIGN KEY([iduser])
REFERENCES [dbo].[USERS] ([id])
GO
ALTER TABLE [dbo].[history] CHECK CONSTRAINT [FK_user_history]
GO
ALTER TABLE [dbo].[historycart]  WITH CHECK ADD  CONSTRAINT [FK_user_historycart] FOREIGN KEY([iduser])
REFERENCES [dbo].[USERS] ([id])
GO
ALTER TABLE [dbo].[historycart] CHECK CONSTRAINT [FK_user_historycart]
GO
ALTER TABLE [dbo].[IMG]  WITH CHECK ADD  CONSTRAINT [FK_list_img_Img] FOREIGN KEY([id_LIST_IMG])
REFERENCES [dbo].[LIST_IMG] ([id])
GO
ALTER TABLE [dbo].[IMG] CHECK CONSTRAINT [FK_list_img_Img]
GO
ALTER TABLE [dbo].[menu]  WITH CHECK ADD  CONSTRAINT [FK_menu_menu] FOREIGN KEY([menuownerid])
REFERENCES [dbo].[menu] ([id])
GO
ALTER TABLE [dbo].[menu] CHECK CONSTRAINT [FK_menu_menu]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [FK_ADMINS_product] FOREIGN KEY([idADMINSLASTMDF])
REFERENCES [dbo].[ADMINS] ([id])
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [FK_ADMINS_product]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [FK_company_product] FOREIGN KEY([idcompany])
REFERENCES [dbo].[company] ([id])
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [FK_company_product]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT_product] FOREIGN KEY([idcontent])
REFERENCES [dbo].[CONTENT] ([id])
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [FK_CONTENT_product]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [FK_list_img_product] FOREIGN KEY([id_list_img])
REFERENCES [dbo].[LIST_IMG] ([id])
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [FK_list_img_product]
GO
ALTER TABLE [dbo].[product]  WITH CHECK ADD  CONSTRAINT [FK_menu_product] FOREIGN KEY([idmenu])
REFERENCES [dbo].[menu] ([id])
GO
ALTER TABLE [dbo].[product] CHECK CONSTRAINT [FK_menu_product]
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_Img_USERS] FOREIGN KEY([idImg])
REFERENCES [dbo].[IMG] ([id])
GO
ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_Img_USERS]
GO
